# Form implementation generated from reading ui file 'UI/arayuz.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180, 780)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 700))
        MainWindow.setStyleSheet("/* Ana Pencere ve Temel Bileşenler */\n"
"QMainWindow {\n"
"    background-color: #0f172a;\n"
"    font-family: \'Segoe UI\', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background-color: #0f172a;\n"
"}\n"
"\n"
"/* Üst Başlık Kartı */\n"
"QFrame#header_frame {\n"
"    background-color: #1e293b;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QLabel#lbl_main_title {\n"
"    color: #f8fafc;\n"
"    font-size: 18pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QLabel#lbl_main_subtitle {\n"
"    color: #94a3b8;\n"
"    font-size: 9.5pt;\n"
"}\n"
"\n"
"/* Üst Durum Rozetleri */\n"
"QLabel.badge_stat {\n"
"    background-color: #0f172a;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"    font-size: 9pt;\n"
"    font-weight: 600;\n"
"    color: #cbd5e1;\n"
"}\n"
"\n"
"/* Oda Kartları */\n"
"QFrame.room_card {\n"
"    background-color: #1e293b;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QFrame.room_card:hover {\n"
"    border: 1px solid #3b82f6;\n"
"}\n"
"\n"
"/* Kart Başlığı */\n"
"QLabel.room_number {\n"
"    color: #f8fafc;\n"
"    font-size: 14pt;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel.room_status {\n"
"    background-color: #0f172a;\n"
"    border-radius: 8px;\n"
"    padding: 4px 12px;\n"
"    font-size: 9.5pt;\n"
"    font-weight: 700;\n"
"    border: 1px solid #334155;\n"
"}\n"
"\n"
"/* Bilgi Kutusu ve Satırları */\n"
"QFrame.info_box {\n"
"    background-color: #0f172a;\n"
"    border: 1px solid #293548;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLabel.info_text {\n"
"    color: #cbd5e1;\n"
"    font-size: 10pt;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel.info_text_price {\n"
"    color: #38bdf8;\n"
"    font-size: 10.5pt;\n"
"    font-weight: 700;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QLabel.info_text_date {\n"
"    color: #94a3b8;\n"
"    font-size: 9.5pt;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* İşlem Butonu */\n"
"QPushButton.btn_action {\n"
"    background-color: #2563eb;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3b82f6;\n"
"    border-radius: 8px;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    padding: 8px 16px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"QPushButton.btn_action:hover {\n"
"    background-color: #1d4ed8;\n"
"    border-color: #60a5fa;\n"
"}\n"
"\n"
"QPushButton.btn_action:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"\n"
"/* Menü ve Durum Çubuğu */\n"
"QMenuBar {\n"
"    background-color: #0f172a;\n"
"    color: #94a3b8;\n"
"    border-bottom: 1px solid #1e293b;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #1e293b;\n"
"    color: #f8fafc;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #0f172a;\n"
"    color: #64748b;\n"
"    border-top: 1px solid #1e293b;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setContentsMargins(20, 16, 20, 16)
        self.mainVerticalLayout.setSpacing(16)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.header_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.header_frame.setMinimumSize(QtCore.QSize(0, 74))
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 74))
        self.header_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_frame.setObjectName("header_frame")
        self.headerHorizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.headerHorizontalLayout.setContentsMargins(20, 10, 20, 10)
        self.headerHorizontalLayout.setObjectName("headerHorizontalLayout")
        self.headerTitlesLayout = QtWidgets.QVBoxLayout()
        self.headerTitlesLayout.setSpacing(2)
        self.headerTitlesLayout.setObjectName("headerTitlesLayout")
        self.lbl_main_title = QtWidgets.QLabel(parent=self.header_frame)
        self.lbl_main_title.setObjectName("lbl_main_title")
        self.headerTitlesLayout.addWidget(self.lbl_main_title)
        self.lbl_main_subtitle = QtWidgets.QLabel(parent=self.header_frame)
        self.lbl_main_subtitle.setObjectName("lbl_main_subtitle")
        self.headerTitlesLayout.addWidget(self.lbl_main_subtitle)
        self.headerHorizontalLayout.addLayout(self.headerTitlesLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerHorizontalLayout.addItem(spacerItem)
        self.lbl_badge_total = QtWidgets.QLabel(parent=self.header_frame)
        self.lbl_badge_total.setObjectName("lbl_badge_total")
        self.headerHorizontalLayout.addWidget(self.lbl_badge_total)
        self.lbl_badge_legend = QtWidgets.QLabel(parent=self.header_frame)
        self.lbl_badge_legend.setObjectName("lbl_badge_legend")
        self.headerHorizontalLayout.addWidget(self.lbl_badge_legend)
        self.mainVerticalLayout.addWidget(self.header_frame)
        self.roomsGridLayout = QtWidgets.QGridLayout()
        self.roomsGridLayout.setSpacing(16)
        self.roomsGridLayout.setObjectName("roomsGridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setObjectName("frame")
        self.vLayout_frame = QtWidgets.QVBoxLayout(self.frame)
        self.vLayout_frame.setContentsMargins(16, 16, 16, 16)
        self.vLayout_frame.setSpacing(12)
        self.vLayout_frame.setObjectName("vLayout_frame")
        self.hLayout_top_frame = QtWidgets.QHBoxLayout()
        self.hLayout_top_frame.setObjectName("hLayout_top_frame")
        self.oda_no = QtWidgets.QLabel(parent=self.frame)
        self.oda_no.setObjectName("oda_no")
        self.hLayout_top_frame.addWidget(self.oda_no)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayout_top_frame.addItem(spacerItem1)
        self.durum = QtWidgets.QLabel(parent=self.frame)
        self.durum.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durum.setObjectName("durum")
        self.hLayout_top_frame.addWidget(self.durum)
        self.vLayout_frame.addLayout(self.hLayout_top_frame)
        self.info_box_frame = QtWidgets.QFrame(parent=self.frame)
        self.info_box_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_box_frame.setObjectName("info_box_frame")
        self.vLayout_info_frame = QtWidgets.QVBoxLayout(self.info_box_frame)
        self.vLayout_info_frame.setContentsMargins(12, 12, 12, 12)
        self.vLayout_info_frame.setSpacing(8)
        self.vLayout_info_frame.setObjectName("vLayout_info_frame")
        self.ad_soyad = QtWidgets.QLabel(parent=self.info_box_frame)
        self.ad_soyad.setObjectName("ad_soyad")
        self.vLayout_info_frame.addWidget(self.ad_soyad)
        self.gunluk_ucret = QtWidgets.QLabel(parent=self.info_box_frame)
        self.gunluk_ucret.setObjectName("gunluk_ucret")
        self.vLayout_info_frame.addWidget(self.gunluk_ucret)
        self.giris = QtWidgets.QLabel(parent=self.info_box_frame)
        self.giris.setObjectName("giris")
        self.vLayout_info_frame.addWidget(self.giris)
        self.cikis = QtWidgets.QLabel(parent=self.info_box_frame)
        self.cikis.setObjectName("cikis")
        self.vLayout_info_frame.addWidget(self.cikis)
        self.vLayout_frame.addWidget(self.info_box_frame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_frame.addItem(spacerItem2)
        self.btn_islem_1 = QtWidgets.QPushButton(parent=self.frame)
        self.btn_islem_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_islem_1.setObjectName("btn_islem_1")
        self.vLayout_frame.addWidget(self.btn_islem_1)
        self.roomsGridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.vLayout_frame_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.vLayout_frame_2.setContentsMargins(16, 16, 16, 16)
        self.vLayout_frame_2.setSpacing(12)
        self.vLayout_frame_2.setObjectName("vLayout_frame_2")
        self.hLayout_top_frame_2 = QtWidgets.QHBoxLayout()
        self.hLayout_top_frame_2.setObjectName("hLayout_top_frame_2")
        self.oda_no_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.oda_no_2.setObjectName("oda_no_2")
        self.hLayout_top_frame_2.addWidget(self.oda_no_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayout_top_frame_2.addItem(spacerItem3)
        self.durum_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.durum_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durum_2.setObjectName("durum_2")
        self.hLayout_top_frame_2.addWidget(self.durum_2)
        self.vLayout_frame_2.addLayout(self.hLayout_top_frame_2)
        self.info_box_frame_2 = QtWidgets.QFrame(parent=self.frame_2)
        self.info_box_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_box_frame_2.setObjectName("info_box_frame_2")
        self.vLayout_info_frame_2 = QtWidgets.QVBoxLayout(self.info_box_frame_2)
        self.vLayout_info_frame_2.setContentsMargins(12, 12, 12, 12)
        self.vLayout_info_frame_2.setSpacing(8)
        self.vLayout_info_frame_2.setObjectName("vLayout_info_frame_2")
        self.ad_soyad_2 = QtWidgets.QLabel(parent=self.info_box_frame_2)
        self.ad_soyad_2.setObjectName("ad_soyad_2")
        self.vLayout_info_frame_2.addWidget(self.ad_soyad_2)
        self.gunluk_ucret_2 = QtWidgets.QLabel(parent=self.info_box_frame_2)
        self.gunluk_ucret_2.setObjectName("gunluk_ucret_2")
        self.vLayout_info_frame_2.addWidget(self.gunluk_ucret_2)
        self.giris_2 = QtWidgets.QLabel(parent=self.info_box_frame_2)
        self.giris_2.setObjectName("giris_2")
        self.vLayout_info_frame_2.addWidget(self.giris_2)
        self.cikis_2 = QtWidgets.QLabel(parent=self.info_box_frame_2)
        self.cikis_2.setObjectName("cikis_2")
        self.vLayout_info_frame_2.addWidget(self.cikis_2)
        self.vLayout_frame_2.addWidget(self.info_box_frame_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_frame_2.addItem(spacerItem4)
        self.btn_islem_2 = QtWidgets.QPushButton(parent=self.frame_2)
        self.btn_islem_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_islem_2.setObjectName("btn_islem_2")
        self.vLayout_frame_2.addWidget(self.btn_islem_2)
        self.roomsGridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setObjectName("frame_3")
        self.vLayout_frame_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.vLayout_frame_3.setContentsMargins(16, 16, 16, 16)
        self.vLayout_frame_3.setSpacing(12)
        self.vLayout_frame_3.setObjectName("vLayout_frame_3")
        self.hLayout_top_frame_3 = QtWidgets.QHBoxLayout()
        self.hLayout_top_frame_3.setObjectName("hLayout_top_frame_3")
        self.oda_no_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.oda_no_3.setObjectName("oda_no_3")
        self.hLayout_top_frame_3.addWidget(self.oda_no_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayout_top_frame_3.addItem(spacerItem5)
        self.durum_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.durum_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durum_3.setObjectName("durum_3")
        self.hLayout_top_frame_3.addWidget(self.durum_3)
        self.vLayout_frame_3.addLayout(self.hLayout_top_frame_3)
        self.info_box_frame_3 = QtWidgets.QFrame(parent=self.frame_3)
        self.info_box_frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_box_frame_3.setObjectName("info_box_frame_3")
        self.vLayout_info_frame_3 = QtWidgets.QVBoxLayout(self.info_box_frame_3)
        self.vLayout_info_frame_3.setContentsMargins(12, 12, 12, 12)
        self.vLayout_info_frame_3.setSpacing(8)
        self.vLayout_info_frame_3.setObjectName("vLayout_info_frame_3")
        self.ad_soyad_3 = QtWidgets.QLabel(parent=self.info_box_frame_3)
        self.ad_soyad_3.setObjectName("ad_soyad_3")
        self.vLayout_info_frame_3.addWidget(self.ad_soyad_3)
        self.gunluk_ucret_3 = QtWidgets.QLabel(parent=self.info_box_frame_3)
        self.gunluk_ucret_3.setObjectName("gunluk_ucret_3")
        self.vLayout_info_frame_3.addWidget(self.gunluk_ucret_3)
        self.giris_3 = QtWidgets.QLabel(parent=self.info_box_frame_3)
        self.giris_3.setObjectName("giris_3")
        self.vLayout_info_frame_3.addWidget(self.giris_3)
        self.cikis_3 = QtWidgets.QLabel(parent=self.info_box_frame_3)
        self.cikis_3.setObjectName("cikis_3")
        self.vLayout_info_frame_3.addWidget(self.cikis_3)
        self.vLayout_frame_3.addWidget(self.info_box_frame_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_frame_3.addItem(spacerItem6)
        self.btn_islem_3 = QtWidgets.QPushButton(parent=self.frame_3)
        self.btn_islem_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_islem_3.setObjectName("btn_islem_3")
        self.vLayout_frame_3.addWidget(self.btn_islem_3)
        self.roomsGridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setObjectName("frame_4")
        self.vLayout_frame_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.vLayout_frame_4.setContentsMargins(16, 16, 16, 16)
        self.vLayout_frame_4.setSpacing(12)
        self.vLayout_frame_4.setObjectName("vLayout_frame_4")
        self.hLayout_top_frame_4 = QtWidgets.QHBoxLayout()
        self.hLayout_top_frame_4.setObjectName("hLayout_top_frame_4")
        self.oda_no_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.oda_no_4.setObjectName("oda_no_4")
        self.hLayout_top_frame_4.addWidget(self.oda_no_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayout_top_frame_4.addItem(spacerItem7)
        self.durum_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.durum_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durum_4.setObjectName("durum_4")
        self.hLayout_top_frame_4.addWidget(self.durum_4)
        self.vLayout_frame_4.addLayout(self.hLayout_top_frame_4)
        self.info_box_frame_4 = QtWidgets.QFrame(parent=self.frame_4)
        self.info_box_frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_box_frame_4.setObjectName("info_box_frame_4")
        self.vLayout_info_frame_4 = QtWidgets.QVBoxLayout(self.info_box_frame_4)
        self.vLayout_info_frame_4.setContentsMargins(12, 12, 12, 12)
        self.vLayout_info_frame_4.setSpacing(8)
        self.vLayout_info_frame_4.setObjectName("vLayout_info_frame_4")
        self.ad_soyad_4 = QtWidgets.QLabel(parent=self.info_box_frame_4)
        self.ad_soyad_4.setObjectName("ad_soyad_4")
        self.vLayout_info_frame_4.addWidget(self.ad_soyad_4)
        self.gunluk_ucret_4 = QtWidgets.QLabel(parent=self.info_box_frame_4)
        self.gunluk_ucret_4.setObjectName("gunluk_ucret_4")
        self.vLayout_info_frame_4.addWidget(self.gunluk_ucret_4)
        self.giris_4 = QtWidgets.QLabel(parent=self.info_box_frame_4)
        self.giris_4.setObjectName("giris_4")
        self.vLayout_info_frame_4.addWidget(self.giris_4)
        self.cikis_4 = QtWidgets.QLabel(parent=self.info_box_frame_4)
        self.cikis_4.setObjectName("cikis_4")
        self.vLayout_info_frame_4.addWidget(self.cikis_4)
        self.vLayout_frame_4.addWidget(self.info_box_frame_4)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_frame_4.addItem(spacerItem8)
        self.btn_islem_4 = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_islem_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_islem_4.setObjectName("btn_islem_4")
        self.vLayout_frame_4.addWidget(self.btn_islem_4)
        self.roomsGridLayout.addWidget(self.frame_4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setObjectName("frame_5")
        self.vLayout_frame_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.vLayout_frame_5.setContentsMargins(16, 16, 16, 16)
        self.vLayout_frame_5.setSpacing(12)
        self.vLayout_frame_5.setObjectName("vLayout_frame_5")
        self.hLayout_top_frame_5 = QtWidgets.QHBoxLayout()
        self.hLayout_top_frame_5.setObjectName("hLayout_top_frame_5")
        self.oda_no_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.oda_no_5.setObjectName("oda_no_5")
        self.hLayout_top_frame_5.addWidget(self.oda_no_5)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayout_top_frame_5.addItem(spacerItem9)
        self.durum_5 = QtWidgets.QLabel(parent=self.frame_5)
        self.durum_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durum_5.setObjectName("durum_5")
        self.hLayout_top_frame_5.addWidget(self.durum_5)
        self.vLayout_frame_5.addLayout(self.hLayout_top_frame_5)
        self.info_box_frame_5 = QtWidgets.QFrame(parent=self.frame_5)
        self.info_box_frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_box_frame_5.setObjectName("info_box_frame_5")
        self.vLayout_info_frame_5 = QtWidgets.QVBoxLayout(self.info_box_frame_5)
        self.vLayout_info_frame_5.setContentsMargins(12, 12, 12, 12)
        self.vLayout_info_frame_5.setSpacing(8)
        self.vLayout_info_frame_5.setObjectName("vLayout_info_frame_5")
        self.ad_soyad_5 = QtWidgets.QLabel(parent=self.info_box_frame_5)
        self.ad_soyad_5.setObjectName("ad_soyad_5")
        self.vLayout_info_frame_5.addWidget(self.ad_soyad_5)
        self.gunluk_ucret_5 = QtWidgets.QLabel(parent=self.info_box_frame_5)
        self.gunluk_ucret_5.setObjectName("gunluk_ucret_5")
        self.vLayout_info_frame_5.addWidget(self.gunluk_ucret_5)
        self.giris_5 = QtWidgets.QLabel(parent=self.info_box_frame_5)
        self.giris_5.setObjectName("giris_5")
        self.vLayout_info_frame_5.addWidget(self.giris_5)
        self.cikis_5 = QtWidgets.QLabel(parent=self.info_box_frame_5)
        self.cikis_5.setObjectName("cikis_5")
        self.vLayout_info_frame_5.addWidget(self.cikis_5)
        self.vLayout_frame_5.addWidget(self.info_box_frame_5)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_frame_5.addItem(spacerItem10)
        self.btn_islem_5 = QtWidgets.QPushButton(parent=self.frame_5)
        self.btn_islem_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_islem_5.setObjectName("btn_islem_5")
        self.vLayout_frame_5.addWidget(self.btn_islem_5)
        self.roomsGridLayout.addWidget(self.frame_5, 1, 1, 1, 1)
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setObjectName("frame_6")
        self.vLayout_frame_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.vLayout_frame_6.setContentsMargins(16, 16, 16, 16)
        self.vLayout_frame_6.setSpacing(12)
        self.vLayout_frame_6.setObjectName("vLayout_frame_6")
        self.hLayout_top_frame_6 = QtWidgets.QHBoxLayout()
        self.hLayout_top_frame_6.setObjectName("hLayout_top_frame_6")
        self.oda_no_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.oda_no_6.setObjectName("oda_no_6")
        self.hLayout_top_frame_6.addWidget(self.oda_no_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hLayout_top_frame_6.addItem(spacerItem11)
        self.durum_6 = QtWidgets.QLabel(parent=self.frame_6)
        self.durum_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durum_6.setObjectName("durum_6")
        self.hLayout_top_frame_6.addWidget(self.durum_6)
        self.vLayout_frame_6.addLayout(self.hLayout_top_frame_6)
        self.info_box_frame_6 = QtWidgets.QFrame(parent=self.frame_6)
        self.info_box_frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_box_frame_6.setObjectName("info_box_frame_6")
        self.vLayout_info_frame_6 = QtWidgets.QVBoxLayout(self.info_box_frame_6)
        self.vLayout_info_frame_6.setContentsMargins(12, 12, 12, 12)
        self.vLayout_info_frame_6.setSpacing(8)
        self.vLayout_info_frame_6.setObjectName("vLayout_info_frame_6")
        self.ad_soyad_6 = QtWidgets.QLabel(parent=self.info_box_frame_6)
        self.ad_soyad_6.setObjectName("ad_soyad_6")
        self.vLayout_info_frame_6.addWidget(self.ad_soyad_6)
        self.gunluk_ucret_6 = QtWidgets.QLabel(parent=self.info_box_frame_6)
        self.gunluk_ucret_6.setObjectName("gunluk_ucret_6")
        self.vLayout_info_frame_6.addWidget(self.gunluk_ucret_6)
        self.giris_6 = QtWidgets.QLabel(parent=self.info_box_frame_6)
        self.giris_6.setObjectName("giris_6")
        self.vLayout_info_frame_6.addWidget(self.giris_6)
        self.cikis_6 = QtWidgets.QLabel(parent=self.info_box_frame_6)
        self.cikis_6.setObjectName("cikis_6")
        self.vLayout_info_frame_6.addWidget(self.cikis_6)
        self.vLayout_frame_6.addWidget(self.info_box_frame_6)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vLayout_frame_6.addItem(spacerItem12)
        self.btn_islem_6 = QtWidgets.QPushButton(parent=self.frame_6)
        self.btn_islem_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_islem_6.setObjectName("btn_islem_6")
        self.vLayout_frame_6.addWidget(self.btn_islem_6)
        self.roomsGridLayout.addWidget(self.frame_6, 1, 2, 1, 1)
        self.mainVerticalLayout.addLayout(self.roomsGridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1180, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otel Rezervasyon ve Oda Yönetim Sistemi"))
        self.lbl_main_title.setText(_translate("MainWindow", "🏨 GRAND SUITE HOTEL"))
        self.lbl_main_subtitle.setText(_translate("MainWindow", "Canlı Oda Durumu ve Rezervasyon Yönetim Paneli"))
        self.lbl_badge_total.setProperty("class", _translate("MainWindow", "badge_stat"))
        self.lbl_badge_total.setText(_translate("MainWindow", "🛏️ Toplam: 6 Oda"))
        self.lbl_badge_legend.setProperty("class", _translate("MainWindow", "badge_stat"))
        self.lbl_badge_legend.setText(_translate("MainWindow", "🟢 Müsait  |  🔴 Dolu"))
        self.frame.setProperty("class", _translate("MainWindow", "room_card"))
        self.oda_no.setProperty("class", _translate("MainWindow", "room_number"))
        self.oda_no.setText(_translate("MainWindow", "Oda 1"))
        self.durum.setProperty("class", _translate("MainWindow", "room_status"))
        self.durum.setText(_translate("MainWindow", "MÜSAİT"))
        self.info_box_frame.setProperty("class", _translate("MainWindow", "info_box"))
        self.ad_soyad.setProperty("class", _translate("MainWindow", "info_text"))
        self.ad_soyad.setText(_translate("MainWindow", "Müşteri: -"))
        self.gunluk_ucret.setProperty("class", _translate("MainWindow", "info_text_price"))
        self.gunluk_ucret.setText(_translate("MainWindow", "Ücret: -"))
        self.giris.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.giris.setText(_translate("MainWindow", "Giriş: -"))
        self.cikis.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.cikis.setText(_translate("MainWindow", "Çıkış: -"))
        self.btn_islem_1.setProperty("class", _translate("MainWindow", "btn_action"))
        self.btn_islem_1.setText(_translate("MainWindow", "Rezervasyon İşlemi"))
        self.frame_2.setProperty("class", _translate("MainWindow", "room_card"))
        self.oda_no_2.setProperty("class", _translate("MainWindow", "room_number"))
        self.oda_no_2.setText(_translate("MainWindow", "Oda 2"))
        self.durum_2.setProperty("class", _translate("MainWindow", "room_status"))
        self.durum_2.setText(_translate("MainWindow", "MÜSAİT"))
        self.info_box_frame_2.setProperty("class", _translate("MainWindow", "info_box"))
        self.ad_soyad_2.setProperty("class", _translate("MainWindow", "info_text"))
        self.ad_soyad_2.setText(_translate("MainWindow", "Müşteri: -"))
        self.gunluk_ucret_2.setProperty("class", _translate("MainWindow", "info_text_price"))
        self.gunluk_ucret_2.setText(_translate("MainWindow", "Ücret: -"))
        self.giris_2.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.giris_2.setText(_translate("MainWindow", "Giriş: -"))
        self.cikis_2.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.cikis_2.setText(_translate("MainWindow", "Çıkış: -"))
        self.btn_islem_2.setProperty("class", _translate("MainWindow", "btn_action"))
        self.btn_islem_2.setText(_translate("MainWindow", "Rezervasyon İşlemi"))
        self.frame_3.setProperty("class", _translate("MainWindow", "room_card"))
        self.oda_no_3.setProperty("class", _translate("MainWindow", "room_number"))
        self.oda_no_3.setText(_translate("MainWindow", "Oda 3"))
        self.durum_3.setProperty("class", _translate("MainWindow", "room_status"))
        self.durum_3.setText(_translate("MainWindow", "MÜSAİT"))
        self.info_box_frame_3.setProperty("class", _translate("MainWindow", "info_box"))
        self.ad_soyad_3.setProperty("class", _translate("MainWindow", "info_text"))
        self.ad_soyad_3.setText(_translate("MainWindow", "Müşteri: -"))
        self.gunluk_ucret_3.setProperty("class", _translate("MainWindow", "info_text_price"))
        self.gunluk_ucret_3.setText(_translate("MainWindow", "Ücret: -"))
        self.giris_3.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.giris_3.setText(_translate("MainWindow", "Giriş: -"))
        self.cikis_3.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.cikis_3.setText(_translate("MainWindow", "Çıkış: -"))
        self.btn_islem_3.setProperty("class", _translate("MainWindow", "btn_action"))
        self.btn_islem_3.setText(_translate("MainWindow", "Rezervasyon İşlemi"))
        self.frame_4.setProperty("class", _translate("MainWindow", "room_card"))
        self.oda_no_4.setProperty("class", _translate("MainWindow", "room_number"))
        self.oda_no_4.setText(_translate("MainWindow", "Oda 4"))
        self.durum_4.setProperty("class", _translate("MainWindow", "room_status"))
        self.durum_4.setText(_translate("MainWindow", "MÜSAİT"))
        self.info_box_frame_4.setProperty("class", _translate("MainWindow", "info_box"))
        self.ad_soyad_4.setProperty("class", _translate("MainWindow", "info_text"))
        self.ad_soyad_4.setText(_translate("MainWindow", "Müşteri: -"))
        self.gunluk_ucret_4.setProperty("class", _translate("MainWindow", "info_text_price"))
        self.gunluk_ucret_4.setText(_translate("MainWindow", "Ücret: -"))
        self.giris_4.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.giris_4.setText(_translate("MainWindow", "Giriş: -"))
        self.cikis_4.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.cikis_4.setText(_translate("MainWindow", "Çıkış: -"))
        self.btn_islem_4.setProperty("class", _translate("MainWindow", "btn_action"))
        self.btn_islem_4.setText(_translate("MainWindow", "Rezervasyon İşlemi"))
        self.frame_5.setProperty("class", _translate("MainWindow", "room_card"))
        self.oda_no_5.setProperty("class", _translate("MainWindow", "room_number"))
        self.oda_no_5.setText(_translate("MainWindow", "Oda 5"))
        self.durum_5.setProperty("class", _translate("MainWindow", "room_status"))
        self.durum_5.setText(_translate("MainWindow", "MÜSAİT"))
        self.info_box_frame_5.setProperty("class", _translate("MainWindow", "info_box"))
        self.ad_soyad_5.setProperty("class", _translate("MainWindow", "info_text"))
        self.ad_soyad_5.setText(_translate("MainWindow", "Müşteri: -"))
        self.gunluk_ucret_5.setProperty("class", _translate("MainWindow", "info_text_price"))
        self.gunluk_ucret_5.setText(_translate("MainWindow", "Ücret: -"))
        self.giris_5.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.giris_5.setText(_translate("MainWindow", "Giriş: -"))
        self.cikis_5.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.cikis_5.setText(_translate("MainWindow", "Çıkış: -"))
        self.btn_islem_5.setProperty("class", _translate("MainWindow", "btn_action"))
        self.btn_islem_5.setText(_translate("MainWindow", "Rezervasyon İşlemi"))
        self.frame_6.setProperty("class", _translate("MainWindow", "room_card"))
        self.oda_no_6.setProperty("class", _translate("MainWindow", "room_number"))
        self.oda_no_6.setText(_translate("MainWindow", "Oda 6"))
        self.durum_6.setProperty("class", _translate("MainWindow", "room_status"))
        self.durum_6.setText(_translate("MainWindow", "MÜSAİT"))
        self.info_box_frame_6.setProperty("class", _translate("MainWindow", "info_box"))
        self.ad_soyad_6.setProperty("class", _translate("MainWindow", "info_text"))
        self.ad_soyad_6.setText(_translate("MainWindow", "Müşteri: -"))
        self.gunluk_ucret_6.setProperty("class", _translate("MainWindow", "info_text_price"))
        self.gunluk_ucret_6.setText(_translate("MainWindow", "Ücret: -"))
        self.giris_6.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.giris_6.setText(_translate("MainWindow", "Giriş: -"))
        self.cikis_6.setProperty("class", _translate("MainWindow", "info_text_date"))
        self.cikis_6.setText(_translate("MainWindow", "Çıkış: -"))
        self.btn_islem_6.setProperty("class", _translate("MainWindow", "btn_action"))
        self.btn_islem_6.setText(_translate("MainWindow", "Rezervasyon İşlemi"))
