# Form implementation generated from reading ui file 'UI/rezervasyon.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(540, 620)
        Dialog.setMinimumSize(QtCore.QSize(500, 580))
        Dialog.setStyleSheet("/* Dialog Ana Arka Planı */\n"
"QDialog {\n"
"    background-color: #0f172a;\n"
"    font-family: \'Segoe UI\', -apple-system, BlinkMacSystemFont, Roboto, sans-serif;\n"
"}\n"
"\n"
"/* Başlık Çerçevesi */\n"
"QFrame#dialog_header {\n"
"    background-color: #1e293b;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QLabel#lbl_dialog_title {\n"
"    color: #f8fafc;\n"
"    font-size: 15pt;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QLabel#lbl_dialog_subtitle {\n"
"    color: #94a3b8;\n"
"    font-size: 9pt;\n"
"}\n"
"\n"
"/* Form Kartı */\n"
"QFrame#form_card {\n"
"    background-color: #1e293b;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"/* Bölüm Başlıkları */\n"
"QLabel.section_title {\n"
"    color: #38bdf8;\n"
"    font-size: 9pt;\n"
"    font-weight: 700;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.5px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Alan Etiketleri */\n"
"QLabel.field_label {\n"
"    color: #cbd5e1;\n"
"    font-size: 9.5pt;\n"
"    font-weight: 600;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Girdi Kutuları */\n"
"QLineEdit, QDateEdit {\n"
"    background-color: #0f172a;\n"
"    color: #f8fafc;\n"
"    border: 1.5px solid #334155;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 10pt;\n"
"    min-height: 22px;\n"
"}\n"
"\n"
"QLineEdit:focus, QDateEdit:focus {\n"
"    border: 1.5px solid #3b82f6;\n"
"    background-color: #0f172a;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #64748b;\n"
"}\n"
"\n"
"/* QDateEdit Özelleştirmesi */\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #334155;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    background-color: #1e293b;\n"
"}\n"
"\n"
"/* Takvim Açılır Penceresi */\n"
"QCalendarWidget QWidget {\n"
"    background-color: #1e293b;\n"
"    color: #f8fafc;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    background-color: #0f172a;\n"
"    color: #f8fafc;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QCalendarWidget QMenu {\n"
"    background-color: #1e293b;\n"
"    color: #f8fafc;\n"
"}\n"
"\n"
"/* Ayırıcı Çizgi */\n"
"QFrame#line_separator {\n"
"    background-color: #334155;\n"
"    max-height: 1px;\n"
"}\n"
"\n"
"/* Butonlar */\n"
"QPushButton#btn_kaydet {\n"
"    background-color: #2563eb;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3b82f6;\n"
"    border-radius: 8px;\n"
"    font-size: 10.5pt;\n"
"    font-weight: 700;\n"
"    padding: 10px 20px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btn_kaydet:hover {\n"
"    background-color: #1d4ed8;\n"
"    border-color: #60a5fa;\n"
"}\n"
"\n"
"QPushButton#btn_kaydet:pressed {\n"
"    background-color: #1e40af;\n"
"}\n"
"\n"
"QPushButton#btn_iptal {\n"
"    background-color: #334155;\n"
"    color: #e2e8f0;\n"
"    border: 1px solid #475569;\n"
"    border-radius: 8px;\n"
"    font-size: 10pt;\n"
"    font-weight: 600;\n"
"    padding: 10px 18px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton#btn_iptal:hover {\n"
"    background-color: #475569;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QPushButton#btn_iptal:pressed {\n"
"    background-color: #1e293b;\n"
"}\n"
"   ")
        self.dialogMainLayout = QtWidgets.QVBoxLayout(Dialog)
        self.dialogMainLayout.setContentsMargins(20, 20, 20, 20)
        self.dialogMainLayout.setSpacing(14)
        self.dialogMainLayout.setObjectName("dialogMainLayout")
        self.dialog_header = QtWidgets.QFrame(parent=Dialog)
        self.dialog_header.setMinimumSize(QtCore.QSize(0, 64))
        self.dialog_header.setMaximumSize(QtCore.QSize(16777215, 64))
        self.dialog_header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dialog_header.setObjectName("dialog_header")
        self.headerVLayout = QtWidgets.QVBoxLayout(self.dialog_header)
        self.headerVLayout.setContentsMargins(16, 10, 16, 10)
        self.headerVLayout.setSpacing(3)
        self.headerVLayout.setObjectName("headerVLayout")
        self.lbl_dialog_title = QtWidgets.QLabel(parent=self.dialog_header)
        self.lbl_dialog_title.setObjectName("lbl_dialog_title")
        self.headerVLayout.addWidget(self.lbl_dialog_title)
        self.lbl_dialog_subtitle = QtWidgets.QLabel(parent=self.dialog_header)
        self.lbl_dialog_subtitle.setObjectName("lbl_dialog_subtitle")
        self.headerVLayout.addWidget(self.lbl_dialog_subtitle)
        self.dialogMainLayout.addWidget(self.dialog_header)
        self.form_card = QtWidgets.QFrame(parent=Dialog)
        self.form_card.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.form_card.setObjectName("form_card")
        self.cardVLayout = QtWidgets.QVBoxLayout(self.form_card)
        self.cardVLayout.setContentsMargins(18, 18, 18, 18)
        self.cardVLayout.setSpacing(14)
        self.cardVLayout.setObjectName("cardVLayout")
        self.lbl_sec_musteri = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_sec_musteri.setObjectName("lbl_sec_musteri")
        self.cardVLayout.addWidget(self.lbl_sec_musteri)
        self.gridMusteri = QtWidgets.QGridLayout()
        self.gridMusteri.setHorizontalSpacing(14)
        self.gridMusteri.setVerticalSpacing(8)
        self.gridMusteri.setObjectName("gridMusteri")
        self.label = QtWidgets.QLabel(parent=self.form_card)
        self.label.setObjectName("label")
        self.gridMusteri.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.form_card)
        self.label_2.setObjectName("label_2")
        self.gridMusteri.addWidget(self.label_2, 0, 1, 1, 1)
        self.txt_ad = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_ad.setClearButtonEnabled(True)
        self.txt_ad.setObjectName("txt_ad")
        self.gridMusteri.addWidget(self.txt_ad, 1, 0, 1, 1)
        self.txt_soyad = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_soyad.setClearButtonEnabled(True)
        self.txt_soyad.setObjectName("txt_soyad")
        self.gridMusteri.addWidget(self.txt_soyad, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.form_card)
        self.label_3.setObjectName("label_3")
        self.gridMusteri.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.form_card)
        self.label_4.setObjectName("label_4")
        self.gridMusteri.addWidget(self.label_4, 2, 1, 1, 1)
        self.txt_tc = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_tc.setMaxLength(11)
        self.txt_tc.setClearButtonEnabled(True)
        self.txt_tc.setObjectName("txt_tc")
        self.gridMusteri.addWidget(self.txt_tc, 3, 0, 1, 1)
        self.txt_tel = QtWidgets.QLineEdit(parent=self.form_card)
        self.txt_tel.setClearButtonEnabled(True)
        self.txt_tel.setObjectName("txt_tel")
        self.gridMusteri.addWidget(self.txt_tel, 3, 1, 1, 1)
        self.cardVLayout.addLayout(self.gridMusteri)
        self.line_separator = QtWidgets.QFrame(parent=self.form_card)
        self.line_separator.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_separator.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_separator.setObjectName("line_separator")
        self.cardVLayout.addWidget(self.line_separator)
        self.lbl_sec_tarih = QtWidgets.QLabel(parent=self.form_card)
        self.lbl_sec_tarih.setObjectName("lbl_sec_tarih")
        self.cardVLayout.addWidget(self.lbl_sec_tarih)
        self.gridTarih = QtWidgets.QGridLayout()
        self.gridTarih.setHorizontalSpacing(14)
        self.gridTarih.setVerticalSpacing(8)
        self.gridTarih.setObjectName("gridTarih")
        self.label_5 = QtWidgets.QLabel(parent=self.form_card)
        self.label_5.setObjectName("label_5")
        self.gridTarih.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.form_card)
        self.label_6.setObjectName("label_6")
        self.gridTarih.addWidget(self.label_6, 0, 1, 1, 1)
        self.date_giris = QtWidgets.QDateEdit(parent=self.form_card)
        self.date_giris.setCalendarPopup(True)
        self.date_giris.setObjectName("date_giris")
        self.gridTarih.addWidget(self.date_giris, 1, 0, 1, 1)
        self.date_cikis = QtWidgets.QDateEdit(parent=self.form_card)
        self.date_cikis.setCalendarPopup(True)
        self.date_cikis.setObjectName("date_cikis")
        self.gridTarih.addWidget(self.date_cikis, 1, 1, 1, 1)
        self.cardVLayout.addLayout(self.gridTarih)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.cardVLayout.addItem(spacerItem)
        self.dialogMainLayout.addWidget(self.form_card)
        self.actionsHLayout = QtWidgets.QHBoxLayout()
        self.actionsHLayout.setSpacing(12)
        self.actionsHLayout.setObjectName("actionsHLayout")
        self.btn_iptal = QtWidgets.QPushButton(parent=Dialog)
        self.btn_iptal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_iptal.setObjectName("btn_iptal")
        self.actionsHLayout.addWidget(self.btn_iptal)
        self.btn_kaydet = QtWidgets.QPushButton(parent=Dialog)
        self.btn_kaydet.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_kaydet.setObjectName("btn_kaydet")
        self.actionsHLayout.addWidget(self.btn_kaydet)
        self.dialogMainLayout.addLayout(self.actionsHLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Oda Rezervasyon İşlemi"))
        self.lbl_dialog_title.setText(_translate("Dialog", "🏨 Yeni Rezervasyon Kaydı"))
        self.lbl_dialog_subtitle.setText(_translate("Dialog", "Müşteri bilgilerini ve konaklama tarihlerini eksiksiz giriniz."))
        self.lbl_sec_musteri.setProperty("class", _translate("Dialog", "section_title"))
        self.lbl_sec_musteri.setText(_translate("Dialog", "👤 MÜŞTERİ BİLGİLERİ"))
        self.label.setProperty("class", _translate("Dialog", "field_label"))
        self.label.setText(_translate("Dialog", "İsim"))
        self.label_2.setProperty("class", _translate("Dialog", "field_label"))
        self.label_2.setText(_translate("Dialog", "Soyisim"))
        self.txt_ad.setPlaceholderText(_translate("Dialog", "Örn: Ahmet"))
        self.txt_soyad.setPlaceholderText(_translate("Dialog", "Örn: Yılmaz"))
        self.label_3.setProperty("class", _translate("Dialog", "field_label"))
        self.label_3.setText(_translate("Dialog", "T.C. Kimlik Numarası"))
        self.label_4.setProperty("class", _translate("Dialog", "field_label"))
        self.label_4.setText(_translate("Dialog", "Telefon Numarası"))
        self.txt_tc.setPlaceholderText(_translate("Dialog", "11 Haneli T.C. No"))
        self.txt_tel.setPlaceholderText(_translate("Dialog", "05XX XXX XX XX"))
        self.lbl_sec_tarih.setProperty("class", _translate("Dialog", "section_title"))
        self.lbl_sec_tarih.setText(_translate("Dialog", "📅 KONAKLAMA TARİHLERİ"))
        self.label_5.setProperty("class", _translate("Dialog", "field_label"))
        self.label_5.setText(_translate("Dialog", "Giriş Tarihi"))
        self.label_6.setProperty("class", _translate("Dialog", "field_label"))
        self.label_6.setText(_translate("Dialog", "Çıkış Tarihi"))
        self.date_giris.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.date_cikis.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy"))
        self.btn_iptal.setText(_translate("Dialog", "Vazgeç"))
        self.btn_kaydet.setText(_translate("Dialog", "💾 Rezervasyonu Kaydet"))
